package layout;

import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JOptionPane;
import servicos.*;
import ClassesUsers.Usuarios;

/**
 * @author Carlos Lenz
 * @author Lucas de Almeida
 */
public class GUI01_Login extends javax.swing.JFrame {
    
    
    private int cont = 0;
    /**
     * Creates new form GUiIPrincipal
     */
    public GUI01_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nivel = new javax.swing.ButtonGroup();
        jpLogin = new javax.swing.JPanel();
        edtSenha = new javax.swing.JPasswordField();
        jlSenha = new javax.swing.JLabel();
        edtId = new javax.swing.JTextField();
        jlId = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        jlAviso = new javax.swing.JLabel();
        jrbtnUser = new javax.swing.JRadioButton();
        jrbtnAdm = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(991, 649));

        jpLogin.setBackground(new java.awt.Color(73, 208, 204));

        edtSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jlSenha.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlSenha.setText("Senha");

        edtId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jlId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlId.setText("ID");
        jlId.setFocusTraversalPolicyProvider(true);

        btnEntrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        jlAviso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jrbtnUser.setBackground(new java.awt.Color(73, 208, 204));
        Nivel.add(jrbtnUser);
        jrbtnUser.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbtnUser.setText("Usuário");

        jrbtnAdm.setBackground(new java.awt.Color(73, 208, 204));
        Nivel.add(jrbtnAdm);
        jrbtnAdm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jrbtnAdm.setSelected(true);
        jrbtnAdm.setText("Administrador");

        javax.swing.GroupLayout jpLoginLayout = new javax.swing.GroupLayout(jpLogin);
        jpLogin.setLayout(jpLoginLayout);
        jpLoginLayout.setHorizontalGroup(
            jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLoginLayout.createSequentialGroup()
                .addContainerGap(320, Short.MAX_VALUE)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLoginLayout.createSequentialGroup()
                        .addComponent(jlAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(283, 283, 283))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpLoginLayout.createSequentialGroup()
                        .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpLoginLayout.createSequentialGroup()
                                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlId)
                                    .addComponent(jlSenha))
                                .addGap(18, 18, 18)
                                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(edtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(edtId, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpLoginLayout.createSequentialGroup()
                                        .addComponent(jrbtnAdm)
                                        .addGap(23, 23, 23)
                                        .addComponent(jrbtnUser)))))
                        .addGap(316, 316, 316))))
        );
        jpLoginLayout.setVerticalGroup(
            jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpLoginLayout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpLoginLayout.createSequentialGroup()
                        .addComponent(jlAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(edtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlId))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlSenha))
                .addGap(18, 18, 18)
                .addGroup(jpLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbtnAdm)
                    .addComponent(jrbtnUser))
                .addGap(21, 21, 21)
                .addComponent(btnEntrar)
                .addContainerGap(318, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void logar(){
        try {
            
            UsuariosServicos us = ServicosFactory.getUsuariosServicos();
            
            Usuarios u = new Usuarios();
            
            u.setId(edtId.getText());
            
            u.setSenha(String.valueOf(edtSenha.getPassword()));
            
            if(jrbtnAdm.isSelected()){
                u.setNivel(jrbtnAdm.getText());
            }else if(jrbtnUser.isSelected()){
                u.setNivel(jrbtnUser.getText());
            }
            
            if(us.validarSenha(u)){
                if(u.getNivel().equals("Administrador")){
                    GUIDesktopADM gda=new GUIDesktopADM();
                    gda.setVisible(true);
                    dispose();
                } else if(u.getNivel().equals("Usuário")){
                    GUIDesktopUser gdu=new GUIDesktopUser();
                    gdu.setVisible(true);
                    dispose();
                }
            }else{
                cont++;
                
                jlAviso.setText(cont+"ª tentativa! Login/senha inválido(s)!");
                
                if(cont==3){
                    System.exit(EXIT_ON_CLOSE);
                }
            }//fecha else
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                    this,
                    "Erro! "+e.getMessage());
        }//fecha catch
    }//fecha logar
    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        logar();
    }//GEN-LAST:event_btnEntrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI01_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI01_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI01_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI01_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI01_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Nivel;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JTextField edtId;
    private javax.swing.JPasswordField edtSenha;
    private javax.swing.JLabel jlAviso;
    private javax.swing.JLabel jlId;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JPanel jpLogin;
    private javax.swing.JRadioButton jrbtnAdm;
    private javax.swing.JRadioButton jrbtnUser;
    // End of variables declaration//GEN-END:variables
}
