package layout;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

/**
 * @author Carlos Lenz
 * @author Lucas de Almeida
 */
public class GUIDesktopADM extends javax.swing.JFrame implements InternalFrameListener{

    private boolean flaggcu = false;
    private boolean flaggcp = false;
    private boolean flagpu = false;
    private boolean flagpp = false;
    
    public GUIDesktopADM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpADM = new javax.swing.JDesktopPane();
        jpADM = new javax.swing.JPanel();
        jlpCadastros = new javax.swing.JLayeredPane();
        jlCadastros = new javax.swing.JLabel();
        jlUsers = new javax.swing.JLabel();
        jlPets = new javax.swing.JLabel();
        jbtnCadPets = new javax.swing.JButton();
        jbtnCadUser = new javax.swing.JButton();
        jlpPesquisa = new javax.swing.JLayeredPane();
        jlPesquisar = new javax.swing.JLabel();
        jlPesqUsers = new javax.swing.JLabel();
        jlPesqPets = new javax.swing.JLabel();
        jbtnPesqUsers = new javax.swing.JButton();
        jbtnPesqPets = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlpCadastros.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlCadastros.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlCadastros.setText("Cadastros");

        jlUsers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlUsers.setText("Usuários");

        jlPets.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlPets.setText("Pets");

        jbtnCadPets.setText("Go");
        jbtnCadPets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCadPetsActionPerformed(evt);
            }
        });

        jbtnCadUser.setText("Go");
        jbtnCadUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCadUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jlpCadastrosLayout = new javax.swing.GroupLayout(jlpCadastros);
        jlpCadastros.setLayout(jlpCadastrosLayout);
        jlpCadastrosLayout.setHorizontalGroup(
            jlpCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpCadastrosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jlCadastros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpCadastrosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jlpCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jlpCadastrosLayout.createSequentialGroup()
                        .addComponent(jlPets)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnCadPets, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jlpCadastrosLayout.createSequentialGroup()
                        .addComponent(jlUsers)
                        .addGap(33, 33, 33)
                        .addComponent(jbtnCadUser, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(296, 296, 296))
        );
        jlpCadastrosLayout.setVerticalGroup(
            jlpCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpCadastrosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jlCadastros)
                .addGap(1, 1, 1)
                .addGroup(jlpCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlUsers)
                    .addComponent(jbtnCadUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpCadastrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPets)
                    .addComponent(jbtnCadPets))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jlpCadastros.setLayer(jlCadastros, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastros.setLayer(jlUsers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastros.setLayer(jlPets, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastros.setLayer(jbtnCadPets, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpCadastros.setLayer(jbtnCadUser, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jlpPesquisa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlPesquisar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jlPesquisar.setText("Pesquisar");

        jlPesqUsers.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlPesqUsers.setText("Usuários");

        jlPesqPets.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlPesqPets.setText("Pets");

        jbtnPesqUsers.setText("Go");
        jbtnPesqUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPesqUsersActionPerformed(evt);
            }
        });

        jbtnPesqPets.setText("Go");
        jbtnPesqPets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPesqPetsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jlpPesquisaLayout = new javax.swing.GroupLayout(jlpPesquisa);
        jlpPesquisa.setLayout(jlpPesquisaLayout);
        jlpPesquisaLayout.setHorizontalGroup(
            jlpPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpPesquisaLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jlPesquisar)
                .addContainerGap(568, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlpPesquisaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jlpPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPesqPets)
                    .addComponent(jlPesqUsers))
                .addGap(37, 37, 37)
                .addGroup(jlpPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtnPesqUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPesqPets, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(298, 298, 298))
        );
        jlpPesquisaLayout.setVerticalGroup(
            jlpPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jlpPesquisaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jlPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jlpPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPesqUsers)
                    .addComponent(jbtnPesqUsers))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jlpPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlPesqPets)
                    .addComponent(jbtnPesqPets))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jlpPesquisa.setLayer(jlPesquisar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpPesquisa.setLayer(jlPesqUsers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpPesquisa.setLayer(jlPesqPets, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpPesquisa.setLayer(jbtnPesqUsers, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jlpPesquisa.setLayer(jbtnPesqPets, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jpADMLayout = new javax.swing.GroupLayout(jpADM);
        jpADM.setLayout(jpADMLayout);
        jpADMLayout.setHorizontalGroup(
            jpADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpADMLayout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jpADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlpCadastros)
                    .addComponent(jlpPesquisa))
                .addGap(67, 67, 67))
        );
        jpADMLayout.setVerticalGroup(
            jpADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpADMLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jlpCadastros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlpPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jdpADMLayout = new javax.swing.GroupLayout(jdpADM);
        jdpADM.setLayout(jdpADMLayout);
        jdpADMLayout.setHorizontalGroup(
            jdpADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpADMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpADM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jdpADMLayout.setVerticalGroup(
            jdpADMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpADMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpADM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jdpADM.setLayer(jpADM, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpADM)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpADM)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCadPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCadPetsActionPerformed
        if(!flaggcp){
            GUICadPet gcp=new GUICadPet();
            jdpADM.add(gcp);
            gcp.setVisible(true);
            flaggcp = true;
            gcp.addInternalFrameListener(this);
        }
    }//GEN-LAST:event_jbtnCadPetsActionPerformed

    private void jbtnCadUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCadUserActionPerformed
        if(!flaggcu){
            GUICadUser gcu = new GUICadUser();
            jdpADM.add(gcu);
            gcu.setVisible(true);
            flaggcu = true;
            gcu.addInternalFrameListener(this);
        }
    }//GEN-LAST:event_jbtnCadUserActionPerformed

    private void jbtnPesqPetsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPesqPetsActionPerformed
        if(!flagpp){
            GUIPesquisaPet pp=new GUIPesquisaPet();
            jdpADM.add(pp);
            pp.setVisible(true);
            flagpp = true;
            pp.addInternalFrameListener(this);
        }
    }//GEN-LAST:event_jbtnPesqPetsActionPerformed

    private void jbtnPesqUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPesqUsersActionPerformed
        if(!flagpu){
            GUIPesquisaUser pu=new GUIPesquisaUser();
            jdpADM.add(pu);
            pu.setVisible(true);
            flagpu = true;
            pu.addInternalFrameListener(this);
        }
    }//GEN-LAST:event_jbtnPesqUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIDesktopADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIDesktopADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIDesktopADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIDesktopADM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIDesktopADM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCadPets;
    private javax.swing.JButton jbtnCadUser;
    private javax.swing.JButton jbtnPesqPets;
    private javax.swing.JButton jbtnPesqUsers;
    private javax.swing.JDesktopPane jdpADM;
    private javax.swing.JLabel jlCadastros;
    private javax.swing.JLabel jlPesqPets;
    private javax.swing.JLabel jlPesqUsers;
    private javax.swing.JLabel jlPesquisar;
    private javax.swing.JLabel jlPets;
    private javax.swing.JLabel jlUsers;
    private javax.swing.JLayeredPane jlpCadastros;
    private javax.swing.JLayeredPane jlpPesquisa;
    private javax.swing.JPanel jpADM;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent e) {
        
    }

    @Override
    public void internalFrameClosing(InternalFrameEvent e) {
        
    }

    @Override
    public void internalFrameClosed(InternalFrameEvent e) {
        if(e.getInternalFrame() instanceof GUICadPet){
            flaggcp = false;
        }else if(e.getInternalFrame() instanceof GUICadUser){
            flaggcu = false;
        }else if(e.getInternalFrame() instanceof GUIPesquisaUser){
            flagpu = false;
        }else if(e.getInternalFrame() instanceof GUIPesquisaPet){
            flagpp = false;
        }
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent e) {
        
    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent e) {
        
    }

    @Override
    public void internalFrameActivated(InternalFrameEvent e) {
        
    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent e) {
        
    }
}
