/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package layout;

/**
 *
 * @author 181820070
 */
public class GUITeste extends javax.swing.JFrame {

    /**
     * Creates new form GUITeste
     */
    public GUITeste() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpTeste = new javax.swing.JDesktopPane();
        jbtnTesteADM = new javax.swing.JButton();
        jbtnTesteCommon = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpTeste.setPreferredSize(new java.awt.Dimension(991, 724));

        jbtnTesteADM.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnTesteADM.setText("Teste ADM");
        jbtnTesteADM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTesteADMActionPerformed(evt);
            }
        });

        jbtnTesteCommon.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnTesteCommon.setText("Teste Common");
        jbtnTesteCommon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTesteCommonActionPerformed(evt);
            }
        });

        jbtnLogin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbtnLogin.setText("Login");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });

        jdpTeste.setLayer(jbtnTesteADM, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpTeste.setLayer(jbtnTesteCommon, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jdpTeste.setLayer(jbtnLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jdpTesteLayout = new javax.swing.GroupLayout(jdpTeste);
        jdpTeste.setLayout(jdpTesteLayout);
        jdpTesteLayout.setHorizontalGroup(
            jdpTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpTesteLayout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addGroup(jdpTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jdpTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jbtnTesteCommon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnTesteADM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(406, Short.MAX_VALUE))
        );
        jdpTesteLayout.setVerticalGroup(
            jdpTesteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdpTesteLayout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(jbtnLogin)
                .addGap(40, 40, 40)
                .addComponent(jbtnTesteADM)
                .addGap(42, 42, 42)
                .addComponent(jbtnTesteCommon)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpTeste, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpTeste, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnTesteADMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTesteADMActionPerformed
           GUIDesktopADM gda=new GUIDesktopADM();
           gda.setVisible(true);
           dispose();
    }//GEN-LAST:event_jbtnTesteADMActionPerformed

    private void jbtnTesteCommonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTesteCommonActionPerformed
        GUIDesktopUser gdu=new GUIDesktopUser();
        gdu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnTesteCommonActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        GUI01_Login gp=new GUI01_Login();
        gp.setVisible(true);
        dispose();
    }//GEN-LAST:event_jbtnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUITeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUITeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUITeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUITeste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUITeste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnTesteADM;
    private javax.swing.JButton jbtnTesteCommon;
    private javax.swing.JDesktopPane jdpTeste;
    // End of variables declaration//GEN-END:variables
}
